@startuml Class Diagram

class APIGateway {
  + process_job()
}

class Factory {
  + register()
  + create_service_instance()
  + get_services()
}

class BaseService {
  {abstract} + register_jobs()
  {abstract} + process_job()
  {abstract} + export_job()
  {abstract} + get_jobs()
}

class DocumentService {
}

class AudioService {
}

class TranslationService {
}

class UserInfoService {

}

class BaseJob{
  {abstract} + process()
  {abstract} + finish()
}

class PDFToWord {

}

class PDFToJPG {

}

class MP3ToWAV {

}

class MP3ToText {

}

class UserInfo {

}

APIGateway --> Factory
Factory --> BaseService
BaseService -->  DocumentService
BaseService -->  AudioService
BaseService -->  TranslationService
BaseService -->  UserInfoService
DocumentService -->  BaseJob
AudioService --> BaseJob
TranslationService -->  BaseJob
UserInfoService -->  BaseJob
BaseJob --> PDFToWord
BaseJob --> PDFToJPG
BaseJob --> MP3ToWAV
BaseJob --> MP3ToText
BaseJob --> UserInfo


@enduml
