@startuml Class Diagram

class APIGateway {
  + process_job()
}

class Factory {
  + register()
  + create_service_instance()
}

class BaseService {
  {abstract} + process_job()
  {abstract} + export_job()
}

class DocumentService {
  + process_job()
  + export_job()
}

class AudioService {
  + process_job()
  + export_job()
}

class TranslationService {
  + process_job()
  + export_job()
}

class UserInfoService {
  + process_job()
  + export_job()
}

class PDFToWordService {
  + process_job()
  + export_job()
}

class PDFToJPGService {
  + process_job()
  + export_job()
}

class MP3ToWAVService {
  + process_job()
  + export_job()
}

class MP3ToTextService {
  + process_job()
  + export_job()
}

class UserInfo {
  + process_job()
  + export_job()
}

APIGateway --> Factory
Factory --> BaseService
BaseService <|-- DocumentService
BaseService <|-- AudioService
BaseService <|-- TranslationService
BaseService <|-- UserInfoService
DocumentService <|-- PDFToWordService
DocumentService <|-- PDFToJPGService
AudioService <|-- MP3ToWAVService
AudioService <|-- MP3ToTextService
TranslationService <|-- TextToTextService
UserInfoService <|-- UserInfo

@enduml
