@startuml System Architecture Diagram

"Client" as client
rectangle "API Gateway" as gateway
rectangle "Base Service" as base_service
rectangle "Factory" as factory

client -- gateway
gateway -- factory
factory -- base_service
base_service -- [DocumentService]
base_service -- [AudioService]
base_service -- [TranslationService]
base_service -- [UserInfoService]
[DocumentService] -- [PDF To Word]
[DocumentService] -- [PDF To JPG]
[AudioService] -- [MP3 To WAV]
[AudioService] -- [MP3 To Text]
[TranslationService] -- [Text To Text]
[UserInfoService] -- [User Info]

@enduml
